
[[Snippets]]
  Description = "interactively browse git branches to checkout"
  Output = ""
  Tag = ["git", "fzf"]
  command = "git branch | fzf | xargs git checkout"

[[Snippets]]
  Description = "Interactively find a file to edit"
  Output = ""
  Tag = ["fzf", "nvim", "editor"]
  command = "nvim (fzf --preview 'bat --color=always {}')"

[[Snippets]]
  Description = "Make a snippet of the previous command"
  Output = ""
  Tag = ["snippets"]
  command = "prev"

[[Snippets]]
  Description = "Interactively select a managed config file to edit"
  Output = ""
  Tag = ["fzf", "chezmoi", "nvim", "editor"]
  command = "chezmoi managed -i files -p absolute | fzf --preview 'bat --color=always {}' | xargs chezmoi edit --apply"
